import React from 'react';
import { useReport } from './ReportContext';

export const ReportFooter: React.FC = () => {
  const { config } = useReport();

  if (!config) return null;

  return (
    <footer className="bg-neutral-10 border-t border-neutral-30 p-4 print:bg-neutral-10">
      <div className="flex items-center justify-between max-w-6xl mx-auto text-xs text-neutral-60">
        <div>
          <p>{config.name} — Confidential</p>
          <p>Generated by MAP Nexus™ Enterprise Platform</p>
        </div>
        <div className="text-right">
          <p>Version {config.version}</p>
          <p>{config.classification.toUpperCase()}</p>
        </div>
      </div>
    </footer>
  );
};
