/* MAP Nexus Dashboard — Embedded Data (Module 00 Compliant) */
/* Source: MAP Presentation Engine — Module 01 */
/* Generated from live MAP execution */

const MAP_DATA = {
  executive: {
    kpi: [{"label": "Overall Readiness", "value": "46%", "status": "warning"}, {"label": "Validation Score", "value": "58.3%", "status": "error"}, {"label": "Migration Status", "value": "BLOCKED", "status": "error"}, {"label": "Blocking Controls", "value": "3", "status": "error"}, {"label": "Failed Rules", "value": "6", "status": "error"}, {"label": "Source Records", "value": "11", "status": "info"}, {"label": "Target Records", "value": "13", "status": "info"}],
    issueDist: [{"label": "Critical", "value": 6, "color": "#D13438"}, {"label": "High", "value": 3, "color": "#FFB900"}, {"label": "Medium", "value": 4, "color": "#FFB900"}, {"label": "Low", "value": 3, "color": "#107C10"}],
    controlStatus: [{"label": "Passed", "value": 2, "color": "#107C10"}, {"label": "Failed", "value": 1, "color": "#FFB900"}, {"label": "Error", "value": 5, "color": "#D13438"}, {"label": "Blocked", "value": 1, "color": "#D13438"}],
    migration: {"name": "Customer Core Banking Migration", "status": "BLOCKED", "readiness_pct": 46, "validation_score": 58.3, "data_quality_score": 80, "blocking_controls": 3, "total_failed_rules": 6, "recommendation": "Resolve critical and high priority findings before proceeding to pilot"}
  },
  migration: {
    entityMapping: [{"source": "accounts_source", "target": "accounts", "source_rows": 4, "target_rows": 3, "record_match_pct": "75.0%", "status": "failed"}, {"source": "balances_source", "target": "balances_target", "source_rows": 3, "target_rows": 3, "record_match_pct": "100.0%", "status": "passed"}, {"source": "customer_accounts_source", "target": "customer_accounts_target", "source_rows": 4, "target_rows": 4, "record_match_pct": "100.0%", "status": "passed"}]
  },
  validation: {
    controls: [{"id": "C01", "name": "Record Completeness", "status": "ERROR", "severity": "HIGH", "total_rules": 3, "passed": 0, "failed": 0, "errors": 3, "details": "Control C01 \u2014 Record Completeness execution completed"}, {"id": "C02", "name": "Financial Integrity", "status": "ERROR", "severity": "CRITICAL", "total_rules": 1, "passed": 0, "failed": 0, "errors": 1, "details": "Control C02 \u2014 Financial Integrity execution completed"}, {"id": "C03", "name": "Referential Integrity", "status": "ERROR", "severity": "LOW", "total_rules": 3, "passed": 0, "failed": 0, "errors": 3, "details": "Control C03 \u2014 Referential Integrity execution completed"}, {"id": "C04", "name": "Column Count Validation", "status": "FAIL", "severity": "HIGH", "total_rules": 3, "passed": 0, "failed": 3, "errors": 0, "details": "Control C04 \u2014 Column Count Validation execution completed"}, {"id": "C05", "name": "Null Drift Detection", "status": "PASS", "severity": "HIGH", "total_rules": 0, "passed": 0, "failed": 0, "errors": 0, "details": "Control C05 \u2014 Null Drift Detection execution completed"}, {"id": "C06", "name": "Duplicate Key Detection", "status": "ERROR", "severity": "CRITICAL", "total_rules": 3, "passed": 1, "failed": 0, "errors": 2, "details": "Control C06 \u2014 Duplicate Key Detection execution completed"}, {"id": "C07", "name": "Data Type Validation", "status": "ERROR", "severity": "HIGH", "total_rules": 3, "passed": 0, "failed": 0, "errors": 3, "details": "Control C07 \u2014 Data Type Validation execution completed"}, {"id": "C09", "name": "Referential Coverage", "status": "PASS", "severity": "HIGH", "total_rules": 0, "passed": 0, "failed": 0, "errors": 0, "details": "Control C09 \u2014 Referential Coverage execution completed"}, {"id": "C010", "name": "Schema Drift Detection", "status": "BLOCKED", "severity": "CRITICAL", "total_rules": 3, "passed": 0, "failed": 3, "errors": 0, "details": "Control C010 \u2014 Schema Drift Detection execution completed"}],
    valDist: [{"label": "Passed", "value": 2, "color": "#107C10"}, {"label": "Failed", "value": 1, "color": "#FFB900"}, {"label": "Error", "value": 5, "color": "#D13438"}, {"label": "Blocked", "value": 1, "color": "#D13438"}],
    summary: {"total": 9, "passed": 2, "failed": 1, "error": 5, "blocked": 1}
  },
  risk: {
    kpi: [{"label": "Overall Risk", "value": "High", "status": "error"}, {"label": "Risk Score", "value": "58.3/100", "status": "error"}, {"label": "Blocking Controls", "value": "3", "status": "error"}, {"label": "Failed Rules", "value": "6", "status": "error"}, {"label": "Schema Drift", "value": "BLOCKED", "status": "error"}, {"label": "Financial Integrity", "value": "ERROR", "status": "error"}, {"label": "Referential Integrity", "value": "ERROR", "status": "error"}],
    risks: [{"id": "R001", "risk": "Schema drift detected in all entities", "severity": "critical", "impact": "Column additions/removals may cause data loss", "mitigation": "Review schema mapping and align definitions", "status": "open"}, {"id": "R002", "risk": "Financial value reconciliation failure", "severity": "critical", "impact": "Financial data integrity compromised", "mitigation": "Investigate financial aggregate discrepancies", "status": "open"}, {"id": "R003", "risk": "Referential integrity validation failure", "severity": "critical", "impact": "Foreign key relationships broken", "mitigation": "Validate FK constraints and relationships", "status": "open"}, {"id": "R004", "risk": "Column count mismatch across entities", "severity": "high", "impact": "Target schema incomplete", "mitigation": "Align column counts between source and target", "status": "open"}, {"id": "R005", "risk": "Data type alignment failure", "severity": "high", "impact": "Type conversion errors during migration", "mitigation": "Standardise data types across platforms", "status": "open"}, {"id": "R006", "risk": "Duplicate key detection partially failed", "severity": "medium", "impact": "Potential duplicate records in target", "mitigation": "Review duplicate detection rules", "status": "open"}],
    goNoGo: {"decision": "NO-GO", "reason": "Migration is BLOCKED. 3 controls are blocking progression with 6 failed rules.", "minimum_requirements": ["All CRITICAL severity findings resolved", "Validation score above 80%", "Zero blocking controls"]}
  },
  quality: {
    dimensions: [{"name": "Completeness", "score": 85, "status": "passed", "details": "Record counts partially validated"}, {"name": "Accuracy", "score": 72, "status": "attention_required", "details": "Financial integrity errors detected"}, {"name": "Consistency", "score": 65, "status": "attention_required", "details": "Schema drift detected across entities"}, {"name": "Timeliness", "score": 90, "status": "passed", "details": "Execution completed within timeout"}, {"name": "Validity", "score": 58, "status": "critical", "details": "Data type and column count mismatches"}, {"name": "Uniqueness", "score": 88, "status": "passed", "details": "Duplicate key detection passed for 1/3 entities"}],
    trend: [{"label": "Week 1", "value": 45}, {"label": "Week 2", "value": 52}, {"label": "Week 3", "value": 61}, {"label": "Week 4", "value": 68}, {"label": "Week 5", "value": 74}, {"label": "Week 6", "value": 80}],
    overallScore: 80
  },
  governance: {
    kpi: [{"label": "Total Controls", "value": "9", "status": "info"}, {"label": "Passed", "value": "2", "status": "success"}, {"label": "Failed", "value": "1", "status": "warning"}, {"label": "Error", "value": "5", "status": "error"}, {"label": "Blocked", "value": "1", "status": "error"}, {"label": "Blocking Controls", "value": "3", "status": "error"}],
    findings: [{"id": "FND-001", "type": "Schema Drift", "description": "Schema drift detected in accounts_source, balances_source, customer_accounts_source", "severity": "critical", "control": "C010", "owner": "Data Engineering", "status": "open", "resolution": "Review and align schema definitions"}, {"id": "FND-002", "type": "Financial Integrity", "description": "Financial value reconciliation failed for balances_source", "severity": "critical", "control": "C02", "owner": "Finance Team", "status": "open", "resolution": "Investigate financial aggregate discrepancies"}, {"id": "FND-003", "type": "Referential Integrity", "description": "Foreign key validation failed for all entities", "severity": "critical", "control": "C03", "owner": "Data Engineering", "status": "open", "resolution": "Validate FK constraints"}, {"id": "FND-004", "type": "Column Count Mismatch", "description": "Column count mismatch in balances_source, customer_accounts_source, accounts_source", "severity": "high", "control": "C04", "owner": "Data Engineering", "status": "open", "resolution": "Align column counts"}, {"id": "FND-005", "type": "Data Type Mismatch", "description": "Source/target column type alignment failed for all entities", "severity": "high", "control": "C07", "owner": "Data Engineering", "status": "open", "resolution": "Standardise data types"}, {"id": "FND-006", "type": "Record Count Mismatch", "description": "Record completeness validation failed for all entities", "severity": "high", "control": "C01", "owner": "Data Engineering", "status": "open", "resolution": "Investigate record count discrepancies"}],
    issueByType: [{"label": "Schema Drift", "value": 1, "color": "#D13438"}, {"label": "Financial Integrity", "value": 1, "color": "#D13438"}, {"label": "Referential Integrity", "value": 1, "color": "#D13438"}, {"label": "Column Count", "value": 1, "color": "#FFB900"}, {"label": "Data Type", "value": 1, "color": "#FFB900"}, {"label": "Record Count", "value": 1, "color": "#FFB900"}],
    severityDist: [{"label": "Critical", "value": 3, "color": "#D13438"}, {"label": "High", "value": 3, "color": "#FFB900"}, {"label": "Medium", "value": 0, "color": "#FFB900"}, {"label": "Low", "value": 0, "color": "#107C10"}],
    summary: {"total_controls": 9, "passed": 2, "failed": 1, "error": 5, "blocked": 1, "blocking_controls": 3, "total_failed_rules": 6}
  },
  progress: {
    phases: [{"name": "Discovery", "progress": 100, "status": "completed"}, {"name": "Profiling", "progress": 100, "status": "completed"}, {"name": "Validation", "progress": 100, "status": "completed"}, {"name": "Migration Controls", "progress": 100, "status": "completed"}, {"name": "Quality Rules", "progress": 100, "status": "completed"}, {"name": "Governance", "progress": 100, "status": "completed"}, {"name": "Reporting", "progress": 100, "status": "completed"}, {"name": "Resolution", "progress": 0, "status": "not_started"}, {"name": "Pilot Migration", "progress": 0, "status": "not_started"}, {"name": "Full Migration", "progress": 0, "status": "not_started"}],
    timeline: {"duration": "0s", "phases_completed": 7, "total_phases": 10}
  },
  landing: {
    product: "MAP Nexus\u2122",
    subtitle: "Migration Assurance Platform",
    scenario: "Scenario 3 \u2014 MIXTURE",
    scenarioName: "Customer Core Banking Migration",
    environment: "Enterprise Demonstration",
    executed: "2026-07-05T08:36:12.697239+00:00",
    status: "BLOCKED",
    readiness: "46%",
    validationScore: "58.3%",
    failedRules: "6",
    blockingControls: "3"
  }
};
