import {
  LayoutDashboard,
  Settings2,
  Database,
  ShieldCheck,
  BarChart3,
  Shield,
  Users,
  Bot,
} from 'lucide-react';
import type { PortalDefinition } from '../types/PortalDefinition';

export const executivePortal: PortalDefinition = {
  id: 'executive',
  name: 'Executive Portal',
  description: 'Real-time insights and analytics for decision makers',
  icon: LayoutDashboard,
  category: 'executive',
  route: '/dashboard/executive',
  defaultRoute: '/dashboard/executive',
  version: '2.0.0',
  owner: 'Platform Team',
  enabled: true,
  status: 'active',
  roles: ['admin', 'manager', 'executive'],
  permissions: ['dashboard:read', 'analytics:read'],
  theme: 'auto',
  navigationGroup: 'main',
  widgets: [
    { id: 'exec-summary', type: 'metric', title: 'Programme Summary', size: 'full', position: { section: 'summary', order: 1 } },
    { id: 'kpi-health', type: 'kpi', title: 'Migration Health', size: 'md', position: { section: 'kpi', order: 1 } },
    { id: 'kpi-controls', type: 'kpi', title: 'Control Success Rate', size: 'md', position: { section: 'kpi', order: 2 } },
    { id: 'kpi-projects', type: 'kpi', title: 'Projects', size: 'md', position: { section: 'kpi', order: 3 } },
    { id: 'kpi-datasets', type: 'kpi', title: 'Datasets', size: 'md', position: { section: 'kpi', order: 4 } },
    { id: 'kpi-rules', type: 'kpi', title: 'Rules Executed', size: 'md', position: { section: 'kpi', order: 5 } },
    { id: 'kpi-controls-exec', type: 'kpi', title: 'Controls Executed', size: 'md', position: { section: 'kpi', order: 6 } },
    { id: 'kpi-failures', type: 'kpi', title: 'Failures', size: 'md', position: { section: 'kpi', order: 7 } },
    { id: 'kpi-warnings', type: 'kpi', title: 'Warnings', size: 'md', position: { section: 'kpi', order: 8 } },
    { id: 'kpi-exceptions', type: 'kpi', title: 'Exceptions', size: 'md', position: { section: 'kpi', order: 9 } },
    { id: 'kpi-audit', type: 'kpi', title: 'Audit Findings', size: 'md', position: { section: 'kpi', order: 10 } },
    { id: 'exec-health-gauge', type: 'gauge', title: 'Migration Health Score', size: 'md', position: { section: 'health', order: 1 } },
    { id: 'exec-risk-status', type: 'status', title: 'Risk Overview', size: 'md', position: { section: 'risk', order: 1 } },
    { id: 'exec-ai-summary', type: 'ai-summary', title: 'AI Executive Summary', size: 'md', position: { section: 'insights', order: 1 } },
    { id: 'exec-actions', type: 'metric', title: 'Quick Actions', size: 'md', position: { section: 'actions', order: 1 } },
    { id: 'exec-notifications', type: 'notification', title: 'Notifications', size: 'md', position: { section: 'notifications', order: 1 } },
    { id: 'exec-reports', type: 'html-report', title: 'Executive Reports', size: 'full', position: { section: 'reports', order: 1 } },
    { id: 'exec-activity', type: 'timeline', title: 'Recent Activity', size: 'full', position: { section: 'activity', order: 1 } },
  ],
  navigation: [
    { id: 'exec-overview', label: 'Overview', path: '/dashboard/executive', icon: LayoutDashboard },
    { id: 'exec-reports', label: 'Reports', path: '/reports', icon: BarChart3 },
    { id: 'exec-ai', label: 'AI Insights', path: '/ai', icon: Bot },
    { id: 'exec-risk', label: 'Risk', path: '/risk', icon: ShieldCheck },
  ],
};

export const operationsPortal: PortalDefinition = {
  id: 'operations',
  name: 'Operations Portal',
  description: 'Day-to-day operations management and monitoring',
  icon: Settings2,
  category: 'operations',
  route: '/operations',
  defaultRoute: '/operations/overview',
  version: '2.0.0',
  owner: 'Operations Team',
  enabled: true,
  status: 'active',
  roles: ['admin', 'manager', 'operator', 'analyst'],
  permissions: ['operations:read', 'operations:manage'],
  theme: 'auto',
  navigationGroup: 'operations',
  widgets: [
    { id: 'ops-running', type: 'kpi', title: 'Running Executions', size: 'md', position: { section: 'execution', order: 1 } },
    { id: 'ops-queued', type: 'kpi', title: 'Queued Jobs', size: 'md', position: { section: 'execution', order: 2 } },
    { id: 'ops-completed', type: 'kpi', title: 'Completed Today', size: 'md', position: { section: 'execution', order: 3 } },
    { id: 'ops-failed', type: 'kpi', title: 'Failed Today', size: 'md', position: { section: 'execution', order: 4 } },
    { id: 'ops-runtime', type: 'kpi', title: 'Avg Runtime', size: 'md', position: { section: 'execution', order: 5 } },
    { id: 'ops-success', type: 'kpi', title: 'Success Rate', size: 'md', position: { section: 'execution', order: 6 } },
    { id: 'ops-queue', type: 'grid', title: 'Execution Queue', size: 'lg', position: { section: 'queues', order: 1 } },
    { id: 'ops-retry-queue', type: 'grid', title: 'Retry Queue', size: 'md', position: { section: 'queues', order: 2 } },
    { id: 'ops-alerts', type: 'notification', title: 'Alerts', size: 'lg', position: { section: 'alerts', order: 1 } },
    { id: 'ops-failures', type: 'kpi', title: 'Failures & Retries', size: 'md', position: { section: 'failures', order: 1 } },
    { id: 'ops-schedules', type: 'task', title: 'Schedule Manager', size: 'md', position: { section: 'schedules', order: 1 } },
    { id: 'ops-monitoring', type: 'timeline', title: 'Recent Activity', size: 'lg', position: { section: 'monitoring', order: 1 } },
    { id: 'ops-health', type: 'status', title: 'System Health', size: 'md', position: { section: 'health', order: 1 } },
    { id: 'ops-ai-summary', type: 'ai-summary', title: 'AI Operations Summary', size: 'full', position: { section: 'ai', order: 1 } },
  ],
  navigation: [
    { id: 'ops-overview', label: 'Dashboard', path: '/operations/overview', icon: LayoutDashboard },
    { id: 'ops-executions', label: 'Executions', path: '/operations/executions', icon: Settings2 },
    { id: 'ops-queues', label: 'Queues', path: '/operations/queues', icon: Settings2 },
    { id: 'ops-schedules', label: 'Schedules', path: '/operations/schedules', icon: Settings2 },
    { id: 'ops-monitoring', label: 'Monitoring', path: '/operations/monitoring', icon: Settings2 },
    { id: 'ops-alerts', label: 'Alerts', path: '/operations/alerts', icon: Settings2 },
    { id: 'ops-retry', label: 'Retry Centre', path: '/operations/retry', icon: Settings2 },
  ],
};

export const migrationPortal: PortalDefinition = {
  id: 'migration',
  name: 'Migration Portal',
  description: 'Data migration management and tracking',
  icon: Database,
  category: 'migration',
  route: '/migration',
  defaultRoute: '/migration/overview',
  version: '2.0.0',
  owner: 'Migration Team',
  enabled: true,
  status: 'active',
  roles: ['admin', 'manager', 'migration-engineer', 'analyst'],
  permissions: ['migration:read', 'migration:execute', 'migration:manage'],
  theme: 'auto',
  navigationGroup: 'operations',
  widgets: [
    { id: 'mig-projects', type: 'kpi', title: 'Active Projects', size: 'md', position: { section: 'overview', order: 1 } },
    { id: 'mig-running', type: 'kpi', title: 'Running Executions', size: 'md', position: { section: 'overview', order: 2 } },
    { id: 'mig-completed', type: 'kpi', title: 'Completed', size: 'md', position: { section: 'overview', order: 3 } },
    { id: 'mig-failed', type: 'kpi', title: 'Failed', size: 'md', position: { section: 'overview', order: 4 } },
    { id: 'mig-rate', type: 'kpi', title: 'Success Rate', size: 'md', position: { section: 'overview', order: 5 } },
    { id: 'mig-health', type: 'kpi', title: 'Migration Health', size: 'md', position: { section: 'overview', order: 6 } },
    { id: 'mig-ai-summary', type: 'ai-summary', title: 'AI Migration Summary', size: 'full', position: { section: 'ai', order: 1 } },
    { id: 'mig-project-list', type: 'grid', title: 'Project List', size: 'full', position: { section: 'projects', order: 1 } },
    { id: 'mig-execution-queue', type: 'grid', title: 'Execution Queue', size: 'full', position: { section: 'execution', order: 1 } },
    { id: 'mig-dataset-inventory', type: 'grid', title: 'Dataset Inventory', size: 'full', position: { section: 'datasets', order: 1 } },
    { id: 'mig-mappings', type: 'grid', title: 'Dataset Mappings', size: 'full', position: { section: 'mappings', order: 1 } },
    { id: 'mig-schedules', type: 'task', title: 'Scheduled Jobs', size: 'full', position: { section: 'schedules', order: 1 } },
    { id: 'mig-history', type: 'timeline', title: 'Migration History', size: 'full', position: { section: 'history', order: 1 } },
    { id: 'mig-workspace', type: 'metric', title: 'Migration Workspace', size: 'full', position: { section: 'workspace', order: 1 } },
  ],
  navigation: [
    { id: 'mig-overview', label: 'Overview', path: '/migration/overview', icon: Database },
    { id: 'mig-projects', label: 'Projects', path: '/migration/projects', icon: Database },
    { id: 'mig-execution', label: 'Execution', path: '/migration/execution', icon: Database },
    { id: 'mig-datasets', label: 'Datasets', path: '/migration/datasets', icon: Database },
    { id: 'mig-mappings', label: 'Mappings', path: '/migration/mappings', icon: Database },
    { id: 'mig-schedules', label: 'Schedules', path: '/migration/schedules', icon: Database },
    { id: 'mig-history', label: 'History', path: '/migration/history', icon: Database },
    { id: 'mig-reports', label: 'Reports', path: '/migration/reports', icon: Database },
    { id: 'mig-workspace', label: 'Workspace', path: '/migration/workspace', icon: Database },
  ],
};

export const governancePortal: PortalDefinition = {
  id: 'governance',
  name: 'Governance Portal',
  description: 'Governance policies, compliance monitoring, and audit trails',
  icon: ShieldCheck,
  category: 'governance',
  route: '/governance',
  defaultRoute: '/governance/overview',
  version: '2.0.0',
  owner: 'Compliance Team',
  enabled: true,
  status: 'active',
  roles: ['admin', 'manager', 'compliance-officer', 'auditor'],
  permissions: ['governance:read', 'governance:manage', 'audit:read'],
  theme: 'auto',
  navigationGroup: 'operations',
  widgets: [
    { id: 'gov-overview', type: 'kpi', title: 'Overall Compliance Score', size: 'md', position: { section: 'overview', order: 1 } },
    { id: 'gov-policy', type: 'kpi', title: 'Policy Compliance', size: 'md', position: { section: 'overview', order: 2 } },
    { id: 'gov-exceptions', type: 'kpi', title: 'Active Exceptions', size: 'md', position: { section: 'overview', order: 3 } },
    { id: 'gov-findings', type: 'kpi', title: 'Audit Findings', size: 'md', position: { section: 'overview', order: 4 } },
    { id: 'gov-health', type: 'kpi', title: 'Governance Health', size: 'md', position: { section: 'overview', order: 5 } },
    { id: 'gov-controls', type: 'kpi', title: 'Control Effectiveness', size: 'md', position: { section: 'overview', order: 6 } },
    { id: 'gov-ai', type: 'ai-summary', title: 'AI Governance Summary', size: 'full', position: { section: 'overview', order: 7 } },
    { id: 'gov-compliance-dash', type: 'status', title: 'Compliance Dashboard', size: 'full', position: { section: 'compliance', order: 1 } },
    { id: 'gov-policies-list', type: 'grid', title: 'Policy Library', size: 'full', position: { section: 'policies', order: 1 } },
    { id: 'gov-controls-list', type: 'grid', title: 'Control Catalogue', size: 'full', position: { section: 'controls', order: 1 } },
    { id: 'gov-exceptions-list', type: 'status', title: 'Open Exceptions', size: 'full', position: { section: 'exceptions', order: 1 } },
    { id: 'gov-risk-chart', type: 'chart', title: 'Enterprise Risk', size: 'full', position: { section: 'risk', order: 1 } },
    { id: 'gov-audit-dash', type: 'status', title: 'Audit Dashboard', size: 'full', position: { section: 'audit', order: 1 } },
    { id: 'gov-reports', type: 'report', title: 'Compliance Reports', size: 'full', position: { section: 'reports', order: 1 } },
    { id: 'gov-workspace', type: 'grid', title: 'Governance Explorer', size: 'full', position: { section: 'workspace', order: 1 } },
  ],
  navigation: [
    { id: 'gov-overview', label: 'Overview', path: '/governance/overview', icon: ShieldCheck },
    { id: 'gov-compliance', label: 'Compliance', path: '/governance/compliance', icon: ShieldCheck },
    { id: 'gov-policies', label: 'Policies', path: '/governance/policies', icon: ShieldCheck },
    { id: 'gov-controls', label: 'Controls', path: '/governance/controls', icon: ShieldCheck },
    { id: 'gov-exceptions', label: 'Exceptions', path: '/governance/exceptions', icon: ShieldCheck },
    { id: 'gov-risk', label: 'Risk Governance', path: '/governance/risk', icon: ShieldCheck },
    { id: 'gov-audit', label: 'Audit Centre', path: '/governance/audit', icon: ShieldCheck },
    { id: 'gov-reports', label: 'Regulatory Reporting', path: '/governance/reports', icon: ShieldCheck },
    { id: 'gov-workspace', label: 'Workspace', path: '/governance/workspace', icon: ShieldCheck },
  ],
};

export const reportingPortal: PortalDefinition = {
  id: 'reporting',
  name: 'Reporting Portal',
  description: 'Report generation, scheduling, and distribution',
  icon: BarChart3,
  category: 'reporting',
  route: '/reports',
  defaultRoute: '/reports/overview',
  version: '2.0.0',
  owner: 'Analytics Team',
  enabled: true,
  status: 'active',
  roles: ['admin', 'manager', 'analyst', 'viewer'],
  permissions: ['reports:read', 'reports:create', 'reports:export'],
  theme: 'auto',
  navigationGroup: 'operations',
  widgets: [
    { id: 'rpt-gen', type: 'kpi', title: 'Reports Generated', size: 'md', position: { section: 'overview', order: 1 } },
    { id: 'rpt-sched', type: 'kpi', title: 'Scheduled Reports', size: 'md', position: { section: 'overview', order: 2 } },
    { id: 'rpt-failed', type: 'kpi', title: 'Failed Reports', size: 'md', position: { section: 'overview', order: 3 } },
    { id: 'rpt-pending', type: 'kpi', title: 'Pending Reports', size: 'md', position: { section: 'overview', order: 4 } },
    { id: 'rpt-usage', type: 'kpi', title: 'Report Usage', size: 'md', position: { section: 'overview', order: 5 } },
    { id: 'rpt-export', type: 'kpi', title: 'Export Activity', size: 'md', position: { section: 'overview', order: 6 } },
    { id: 'rpt-ai', type: 'ai-summary', title: 'AI Report Summary', size: 'full', position: { section: 'overview', order: 7 } },
    { id: 'rpt-exec', type: 'html-report', title: 'Executive Reports', size: 'full', position: { section: 'executive', order: 1 } },
    { id: 'rpt-ops', type: 'html-report', title: 'Operational Reports', size: 'full', position: { section: 'operational', order: 1 } },
    { id: 'rpt-mig', type: 'html-report', title: 'Migration Reports', size: 'full', position: { section: 'migration', order: 1 } },
    { id: 'rpt-val', type: 'html-report', title: 'Validation Reports', size: 'full', position: { section: 'validation', order: 1 } },
    { id: 'rpt-gov', type: 'html-report', title: 'Governance Reports', size: 'full', position: { section: 'governance', order: 1 } },
    { id: 'rpt-aud', type: 'audit-report', title: 'Audit Reports', size: 'full', position: { section: 'audit', order: 1 } },
    { id: 'rpt-reg', type: 'html-report', title: 'Regulatory Reports', size: 'full', position: { section: 'regulatory', order: 1 } },
    { id: 'rpt-scheduled', type: 'status', title: 'Scheduled Reports', size: 'full', position: { section: 'scheduled', order: 1 } },
    { id: 'rpt-templates', type: 'grid', title: 'Report Templates', size: 'full', position: { section: 'templates', order: 1 } },
    { id: 'rpt-dist', type: 'status', title: 'Distribution', size: 'full', position: { section: 'distribution', order: 1 } },
    { id: 'rpt-workspace', type: 'grid', title: 'Reporting Workspace', size: 'full', position: { section: 'workspace', order: 1 } },
  ],
  navigation: [
    { id: 'rpt-overview', label: 'Overview', path: '/reports/overview', icon: BarChart3 },
    { id: 'rpt-executive', label: 'Executive Reports', path: '/reports/executive', icon: BarChart3 },
    { id: 'rpt-operational', label: 'Operational Reports', path: '/reports/operational', icon: BarChart3 },
    { id: 'rpt-migration', label: 'Migration Reports', path: '/reports/migration', icon: BarChart3 },
    { id: 'rpt-validation', label: 'Validation Reports', path: '/reports/validation', icon: BarChart3 },
    { id: 'rpt-governance', label: 'Governance Reports', path: '/reports/governance', icon: BarChart3 },
    { id: 'rpt-audit', label: 'Audit Reports', path: '/reports/audit', icon: BarChart3 },
    { id: 'rpt-regulatory', label: 'Regulatory Reports', path: '/reports/regulatory', icon: BarChart3 },
    { id: 'rpt-scheduled', label: 'Scheduled Reports', path: '/reports/scheduled', icon: BarChart3 },
    { id: 'rpt-templates', label: 'Templates', path: '/reports/templates', icon: BarChart3 },
    { id: 'rpt-distribution', label: 'Distribution', path: '/reports/distribution', icon: BarChart3 },
    { id: 'rpt-workspace', label: 'Workspace', path: '/reports/workspace', icon: BarChart3 },
  ],
};

export const securityPortal: PortalDefinition = {
  id: 'security',
  name: 'Security Portal',
  description: 'Security monitoring, access control, and threat detection',
  icon: Shield,
  category: 'security',
  route: '/security',
  defaultRoute: '/security/overview',
  version: '2.0.0',
  owner: 'Security Team',
  enabled: true,
  status: 'active',
  roles: ['admin', 'security-analyst'],
  permissions: ['security:read', 'security:manage', 'access:manage'],
  theme: 'auto',
  navigationGroup: 'system',
  widgets: [
    { id: 'sec-health', type: 'kpi', title: 'Security Health Score', size: 'md', position: { section: 'overview', order: 1 } },
    { id: 'sec-sessions', type: 'kpi', title: 'Active Sessions', size: 'md', position: { section: 'overview', order: 2 } },
    { id: 'sec-failed', type: 'kpi', title: 'Failed Logins', size: 'md', position: { section: 'overview', order: 3 } },
    { id: 'sec-mfa', type: 'kpi', title: 'MFA Adoption', size: 'md', position: { section: 'overview', order: 4 } },
    { id: 'sec-cred', type: 'kpi', title: 'Credential Status', size: 'md', position: { section: 'overview', order: 5 } },
    { id: 'sec-cert', type: 'kpi', title: 'Certificate Status', size: 'md', position: { section: 'overview', order: 6 } },
    { id: 'sec-enc', type: 'kpi', title: 'Encryption Status', size: 'md', position: { section: 'overview', order: 7 } },
    { id: 'sec-comp', type: 'kpi', title: 'Compliance Status', size: 'md', position: { section: 'overview', order: 8 } },
    { id: 'sec-threat', type: 'ai-summary', title: 'Threat Summary', size: 'full', position: { section: 'overview', order: 9 } },
    { id: 'sec-cred-mgmt', type: 'status', title: 'Credential Management', size: 'full', position: { section: 'credentials', order: 1 } },
    { id: 'sec-enc-mgmt', type: 'status', title: 'Encryption Management', size: 'full', position: { section: 'encryption', order: 1 } },
    { id: 'sec-key-mgmt', type: 'status', title: 'Key Management', size: 'full', position: { section: 'keys', order: 1 } },
    { id: 'sec-cert-mgmt', type: 'status', title: 'Certificate Management', size: 'full', position: { section: 'certificates', order: 1 } },
    { id: 'sec-idp', type: 'status', title: 'Identity Providers', size: 'full', position: { section: 'identity', order: 1 } },
    { id: 'sec-auth', type: 'status', title: 'Authentication Policies', size: 'full', position: { section: 'authentication', order: 1 } },
    { id: 'sec-mfa-mgmt', type: 'status', title: 'Multi-Factor Authentication', size: 'full', position: { section: 'mfa', order: 1 } },
    { id: 'sec-sess', type: 'status', title: 'Session Management', size: 'full', position: { section: 'sessions', order: 1 } },
    { id: 'sec-api', type: 'status', title: 'API Security', size: 'full', position: { section: 'api', order: 1 } },
    { id: 'sec-audit', type: 'status', title: 'Audit Logs', size: 'full', position: { section: 'audit', order: 1 } },
    { id: 'sec-events', type: 'status', title: 'Security Events', size: 'full', position: { section: 'events', order: 1 } },
    { id: 'sec-threat-mgmt', type: 'status', title: 'Threat Monitoring', size: 'full', position: { section: 'threats', order: 1 } },
    { id: 'sec-comp-status', type: 'status', title: 'Compliance Status', size: 'full', position: { section: 'compliance', order: 1 } },
    { id: 'sec-dash', type: 'kpi', title: 'Security Dashboard', size: 'full', position: { section: 'dashboard', order: 1 } },
  ],
  navigation: [
    { id: 'sec-overview', label: 'Overview', path: '/security/overview', icon: Shield },
    { id: 'sec-credentials', label: 'Credentials', path: '/security/credentials', icon: Shield },
    { id: 'sec-encryption', label: 'Encryption', path: '/security/encryption', icon: Shield },
    { id: 'sec-keys', label: 'Keys', path: '/security/keys', icon: Shield },
    { id: 'sec-certificates', label: 'Certificates', path: '/security/certificates', icon: Shield },
    { id: 'sec-identity', label: 'Identity Providers', path: '/security/identity-providers', icon: Shield },
    { id: 'sec-auth', label: 'Authentication', path: '/security/authentication', icon: Shield },
    { id: 'sec-mfa', label: 'MFA', path: '/security/mfa', icon: Shield },
    { id: 'sec-sessions', label: 'Sessions', path: '/security/sessions', icon: Shield },
    { id: 'sec-api', label: 'API Security', path: '/security/api-security', icon: Shield },
    { id: 'sec-audit', label: 'Audit Logs', path: '/security/audit-logs', icon: Shield },
    { id: 'sec-events', label: 'Security Events', path: '/security/security-events', icon: Shield },
    { id: 'sec-threats', label: 'Threat Monitoring', path: '/security/threat-monitoring', icon: Shield },
    { id: 'sec-compliance', label: 'Compliance', path: '/security/compliance', icon: Shield },
    { id: 'sec-dashboard', label: 'Security Dashboard', path: '/security/dashboard', icon: Shield },
  ],
};

export const administrationPortal: PortalDefinition = {
  id: 'administration',
  name: 'Administration Portal',
  description: 'System administration, user management, and configuration',
  icon: Users,
  category: 'administration',
  route: '/administration',
  defaultRoute: '/administration/overview',
  version: '2.0.0',
  owner: 'Platform Team',
  enabled: true,
  status: 'active',
  roles: ['admin'],
  permissions: ['admin:read', 'admin:manage', 'users:manage', 'roles:manage'],
  theme: 'auto',
  navigationGroup: 'system',
  widgets: [
    { id: 'adm-users-kpi', type: 'kpi', title: 'Active Users', size: 'md', position: { section: 'overview', order: 1 } },
    { id: 'adm-tenants-kpi', type: 'kpi', title: 'Active Tenants', size: 'md', position: { section: 'overview', order: 2 } },
    { id: 'adm-orgs-kpi', type: 'kpi', title: 'Organisations', size: 'md', position: { section: 'overview', order: 3 } },
    { id: 'adm-sessions-kpi', type: 'kpi', title: 'Active Sessions', size: 'md', position: { section: 'overview', order: 4 } },
    { id: 'adm-jobs-kpi', type: 'kpi', title: 'Scheduled Jobs', size: 'md', position: { section: 'overview', order: 5 } },
    { id: 'adm-health-kpi', type: 'kpi', title: 'Platform Health', size: 'md', position: { section: 'overview', order: 6 } },
    { id: 'adm-licence-kpi', type: 'kpi', title: 'Licence Usage', size: 'md', position: { section: 'overview', order: 7 } },
    { id: 'adm-features-kpi', type: 'kpi', title: 'Feature Status', size: 'md', position: { section: 'overview', order: 8 } },
    { id: 'adm-alerts', type: 'ai-summary', title: 'System Alerts', size: 'full', position: { section: 'overview', order: 9 } },
    { id: 'adm-tenants', type: 'status', title: 'Tenant Management', size: 'full', position: { section: 'tenants', order: 1 } },
    { id: 'adm-orgs', type: 'status', title: 'Organisation Management', size: 'full', position: { section: 'organisations', order: 1 } },
    { id: 'adm-users-list', type: 'status', title: 'User Management', size: 'full', position: { section: 'users', order: 1 } },
    { id: 'adm-roles', type: 'status', title: 'Role Management', size: 'full', position: { section: 'roles', order: 1 } },
    { id: 'adm-permissions', type: 'status', title: 'Permission Management', size: 'full', position: { section: 'permissions', order: 1 } },
    { id: 'adm-subscriptions', type: 'status', title: 'Subscription Management', size: 'full', position: { section: 'subscriptions', order: 1 } },
    { id: 'adm-licensing', type: 'status', title: 'Licensing', size: 'full', position: { section: 'licensing', order: 1 } },
    { id: 'adm-config', type: 'status', title: 'Platform Configuration', size: 'full', position: { section: 'configuration', order: 1 } },
    { id: 'adm-features', type: 'status', title: 'Feature Flags', size: 'full', position: { section: 'features', order: 1 } },
    { id: 'adm-settings', type: 'status', title: 'System Settings', size: 'full', position: { section: 'settings', order: 1 } },
    { id: 'adm-scheduler', type: 'status', title: 'Job Scheduler', size: 'full', position: { section: 'scheduler', order: 1 } },
    { id: 'adm-notifications', type: 'status', title: 'Notification Management', size: 'full', position: { section: 'notifications', order: 1 } },
    { id: 'adm-environment', type: 'status', title: 'Environment Management', size: 'full', position: { section: 'environment', order: 1 } },
    { id: 'adm-maintenance', type: 'status', title: 'Maintenance Centre', size: 'full', position: { section: 'maintenance', order: 1 } },
    { id: 'adm-health', type: 'kpi', title: 'Health Monitoring', size: 'full', position: { section: 'health', order: 1 } },
    { id: 'adm-dashboard', type: 'kpi', title: 'Administration Dashboard', size: 'full', position: { section: 'dashboard', order: 1 } },
  ],
  navigation: [
    { id: 'adm-overview', label: 'Overview', path: '/administration/overview', icon: Users },
    { id: 'adm-tenants', label: 'Tenants', path: '/administration/tenants', icon: Users },
    { id: 'adm-organisations', label: 'Organisations', path: '/administration/organisations', icon: Users },
    { id: 'adm-users', label: 'Users', path: '/administration/users', icon: Users },
    { id: 'adm-roles', label: 'Roles', path: '/administration/roles', icon: Users },
    { id: 'adm-permissions', label: 'Permissions', path: '/administration/permissions', icon: Users },
    { id: 'adm-subscriptions', label: 'Subscriptions', path: '/administration/subscriptions', icon: Users },
    { id: 'adm-licensing', label: 'Licensing', path: '/administration/licensing', icon: Users },
    { id: 'adm-configuration', label: 'Platform Configuration', path: '/administration/configuration', icon: Users },
    { id: 'adm-feature-flags', label: 'Feature Flags', path: '/administration/feature-flags', icon: Users },
    { id: 'adm-system-settings', label: 'System Settings', path: '/administration/system-settings', icon: Users },
    { id: 'adm-scheduler', label: 'Scheduler', path: '/administration/scheduler', icon: Users },
    { id: 'adm-notifications', label: 'Notifications', path: '/administration/notifications', icon: Users },
    { id: 'adm-environment', label: 'Environment', path: '/administration/environment', icon: Users },
    { id: 'adm-maintenance', label: 'Maintenance', path: '/administration/maintenance', icon: Users },
    { id: 'adm-health', label: 'Platform Health', path: '/administration/health', icon: Users },
    { id: 'adm-dashboard', label: 'Administration Dashboard', path: '/administration/dashboard', icon: Users },
  ],
};

export const aiPortal: PortalDefinition = {
  id: 'ai',
  name: 'AI Portal',
  description: 'AI-powered insights, recommendations, and assistant',
  icon: Bot,
  category: 'ai',
  route: '/ai',
  defaultRoute: '/ai/assistant',
  version: '2.0.0',
  owner: 'AI Team',
  enabled: true,
  status: 'active',
  roles: ['admin', 'manager', 'analyst', 'ai-user'],
  permissions: ['ai:read', 'ai:execute', 'ai:manage'],
  theme: 'auto',
  navigationGroup: 'system',
  widgets: [
    { id: 'ai-assistant', type: 'ai-summary', title: 'AI Assistant', size: 'full', position: { section: 'assistant', order: 1 } },
    { id: 'ai-insights', type: 'ai-insight', title: 'AI Insights', size: 'lg', position: { section: 'insights', order: 1 } },
    { id: 'ai-recommendations', type: 'ai-recommendation', title: 'Recommendations', size: 'lg', position: { section: 'recommendations', order: 1 } },
  ],
  navigation: [
    { id: 'ai-assistant', label: 'Assistant', path: '/ai/assistant', icon: Bot },
    { id: 'ai-insights', label: 'Insights', path: '/ai/insights', icon: Bot },
    { id: 'ai-prompts', label: 'Prompts', path: '/ai/prompts', icon: Bot },
  ],
};

export const allPortals: PortalDefinition[] = [
  executivePortal,
  operationsPortal,
  migrationPortal,
  governancePortal,
  reportingPortal,
  securityPortal,
  administrationPortal,
  aiPortal,
];

export const getPortalById = (id: string): PortalDefinition | undefined => {
  return allPortals.find((portal) => portal.id === id);
};

export const getPortalByRoute = (route: string): PortalDefinition | undefined => {
  return allPortals.find(
    (portal) => route.startsWith(portal.route) || portal.route === route
  );
};

export const getPortalsByCategory = (category: PortalDefinition['category']): PortalDefinition[] => {
  return allPortals.filter((portal) => portal.category === category);
};

export const getEnabledPortals = (): PortalDefinition[] => {
  return allPortals.filter((portal) => portal.enabled && portal.status === 'active');
};
