import { Download, Share2, Printer } from 'lucide-react';

interface ReportPreviewProps {
  reportName?: string;
}

export const ReportPreview: React.FC<ReportPreviewProps> = ({
  reportName = 'Executive Dashboard Report',
}) => {
  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold text-neutral-100">Report Preview</h1>
          <p className="text-neutral-60">{reportName}</p>
        </div>
        <div className="flex items-center gap-2">
          <button className="flex items-center gap-2 px-3 py-2 border border-neutral-30 rounded-lg text-sm hover:bg-neutral-50">
            <Download className="w-4 h-4" />
            Export
          </button>
          <button className="flex items-center gap-2 px-3 py-2 border border-neutral-30 rounded-lg text-sm hover:bg-neutral-50">
            <Share2 className="w-4 h-4" />
            Share
          </button>
          <button className="flex items-center gap-2 px-3 py-2 border border-neutral-30 rounded-lg text-sm hover:bg-neutral-50">
            <Printer className="w-4 h-4" />
            Print
          </button>
        </div>
      </div>

      <div className="bg-white border border-neutral-20 rounded-lg overflow-hidden">
        <div className="bg-gradient-to-br from-primary-600 to-primary-800 text-white p-12 text-center">
          <h2 className="text-3xl font-bold mb-2">{reportName}</h2>
          <p className="text-primary-20">Generated by MAP Nexus™ Enterprise Platform</p>
          <p className="text-primary-30 text-sm mt-2">July 2026</p>
        </div>

        <div className="p-6 space-y-6">
          <section>
            <h3 className="text-lg font-semibold text-neutral-100 mb-3 border-l-4 border-primary-500 pl-3">
              Executive Summary
            </h3>
            <p className="text-neutral-70 leading-relaxed">
              This report provides a comprehensive overview of key performance indicators and strategic insights
              for the current reporting period. All critical metrics are within expected ranges with notable
              improvements in migration velocity and governance compliance.
            </p>
          </section>

          <section>
            <h3 className="text-lg font-semibold text-neutral-100 mb-3 border-l-4 border-primary-500 pl-3">
              Key Performance Indicators
            </h3>
            <div className="grid grid-cols-3 gap-4">
              {[
                { label: 'Migration Progress', value: '87%' },
                { label: 'Compliance Score', value: '94%' },
                { label: 'Risk Rating', value: 'Low' },
              ].map((kpi) => (
                <div key={kpi.label} className="bg-neutral-50 rounded-lg p-4 text-center">
                  <p className="text-2xl font-bold text-primary-600">{kpi.value}</p>
                  <p className="text-sm text-neutral-60">{kpi.label}</p>
                </div>
              ))}
            </div>
          </section>

          <section>
            <h3 className="text-lg font-semibold text-neutral-100 mb-3 border-l-4 border-primary-500 pl-3">
              Recommendations
            </h3>
            <ul className="space-y-2 text-neutral-70">
              <li className="flex items-start gap-2">
                <span className="text-primary-500 mt-1">→</span>
                Accelerate data validation for Project Alpha
              </li>
              <li className="flex items-start gap-2">
                <span className="text-primary-500 mt-1">→</span>
                Schedule quarterly governance review
              </li>
              <li className="flex items-start gap-2">
                <span className="text-primary-500 mt-1">→</span>
                Review security audit findings
              </li>
            </ul>
          </section>
        </div>
      </div>
    </div>
  );
};
