import { useReportViewer } from './ReportViewerContext';
import { ViewerPageIndicator } from './components/widgets/ViewerPageIndicator';

export const ReportFooter = () => {
  const { reportConfig } = useReportViewer();

  return (
    <div className="flex items-center justify-between px-8 py-4 border-t border-neutral-200 bg-neutral-5 print:bg-neutral-5 text-xs text-neutral-50">
      <div>
        <p>{reportConfig?.name ?? 'Report'} — Confidential</p>
        <p>Generated by MAP Nexus™ Enterprise Platform</p>
      </div>
      <ViewerPageIndicator />
    </div>
  );
};
